# Generated by Django 2.1.8 on 2019-05-21 09:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtail_tag_manager', '0013_auto_20190506_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('wtm_include_children', models.BooleanField(default=False, help_text='Also include these tags on all children of this page.', verbose_name='Include children')),
                ('content', wagtail.fields.RichTextField()),
                ('wtm_tags', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The tags to include when this page is loaded.', related_name='pages', to='wagtail_tag_manager.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
