# Generated by Django 2.1.7 on 2019-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0008_auto_load_rename'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tags',
            field=models.ManyToManyField(help_text='The tags to include when this page is loaded.', to='wagtail_tag_manager.Tag'),
        ),
    ]
