# Generated by Django 4.2.9 on 2024-01-25 14:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_tag_manager", "0019_cookieconsentsettings"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggableContentPage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.contentpage",
                    ),
                ),
                (
                    "wtm_include_children",
                    models.BooleanField(
                        default=False,
                        help_text="Also include these tags on all children of this page.",
                        verbose_name="Include children",
                    ),
                ),
                (
                    "wtm_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="The tags to include when this page is loaded.",
                        related_name="pages",
                        to="wagtail_tag_manager.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pages.contentpage", models.Model),
        ),
    ]
