# Generated by Django 2.0.3 on 2018-03-24 08:15

from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tag_type', models.CharField(choices=[('functional', 'Functional'), ('analytical', 'Analytical'), ('traceable', 'Traceable')], default='functional', max_length=10)),
                ('tag_location', models.CharField(choices=[('top_head', 'Top of head tag'), ('bottom_head', 'Bottom of head tag'), ('top_body', 'Top of body tag'), ('bottom_body', 'Bottom of body tag')], default='top_head', max_length=12)),
                ('tag_loading', models.CharField(choices=[('instant_load', 'Instant'), ('lazy_load', 'Lazy')], default='instant_load', max_length=12)),
                ('content', models.TextField()),
                ('value', models.TextField(editable=False)),
            ],
        ),
    ]
