# Generated by Django 2.0.3 on 2018-03-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
    ]
