# Generated by Django 2.0.3 on 2018-03-25 07:30

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0003_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
