# Generated by Django 2.1.3 on 2018-12-06 15:30

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0003_auto_20181206_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiedeclaration',
            name='duration_period',
        ),
        migrations.RemoveField(
            model_name='cookiedeclaration',
            name='duration_value',
        ),
        migrations.AddField(
            model_name='cookiedeclaration',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
