# Generated by Django 2.0.3 on 2018-03-25 18:45

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0004_auto_20180325_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('variable_type', models.CharField(choices=[('HTTP', (('path', 'Path'), ('META__HTTP_HOST', 'Host'), ('META__HTTP_USER_AGENT', 'User agent'))), ('User', (('user', 'User'), ('session', 'Session'))), ('Wagtail', (('site', 'Site'), ('page', 'Page'))), ('_cookie', 'Cookie'), ('_random', 'Random number')], max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
