# Generated by Django 2.0.3 on 2018-03-30 16:41

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0005_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_type',
            field=models.CharField(choices=[('HTTP', (('path', 'Path'),)), ('User', (('user.pk', 'User'), ('session.session_key', 'Session'))), ('Wagtail', (('site', 'Site'),)), ('Other', (('_cookie+', 'Cookie'), ('_random', 'Random number')))], max_length=255),
        ),
    ]
