# Generated by Django 2.1.4 on 2019-01-30 09:31

import wagtail.core.fields
import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtail_tag_manager', '0005_auto_20181227_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieBarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title that should appear on the cookie bar. Leave empty for the default value.', max_length=50, null=True)),
                ('text', wagtail.core.fields.RichTextField(blank=True, help_text='The text that should appear on the cookie bar. Leave empty for the default value.', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
