# Generated by Django 2.0.6 on 2018-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0007_auto_20180815_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pattern', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='constant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_loading',
            field=models.CharField(choices=[('instant_load', 'Instant'), ('lazy_load', 'Lazy'), ('passive_load', 'Passive')], default='instant_load', max_length=12),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
