# Generated by Django 2.0.6 on 2018-09-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0009_auto_20180905_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='passive',
        ),
    ]
