# Generated by Django 2.1.8 on 2019-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0009_auto_20190401_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiedeclaration',
            name='cookie_type',
            field=models.CharField(blank=True, choices=[('functional', 'Functional'), ('analytical', 'Analytical'), ('delayed', 'Delayed'), ('traceable', 'Traceable')], help_text='The type of functionality this cookie supports.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('functional', 'Functional'), ('analytical', 'Analytical'), ('delayed', 'Delayed'), ('traceable', 'Traceable')], default='functional', help_text='The purpose of this tag. Will decide if and when this tag is loaded on a per-user basis.', max_length=100),
        ),
    ]
