# Generated by Django 2.1.8 on 2019-05-01 10:49

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0010_auto_20190403_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='variable_type',
            field=models.CharField(choices=[('HTTP', (('_repath+', 'Path with regex'),)), ('Other', (('_cookie+', 'Cookie'),))], help_text='<b>Path with regex:</b> the path of the visited page after applying a regex search.<br/><b>Cookie:</b> the value of a cookie, when available.', max_length=255),
        ),
    ]
