# Generated by Django 2.0.8 on 2018-09-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0011_trigger_tags'),
        ('wagtail_tag_manager', '0008_auto_20180905_2019'),
    ]

    operations = [
    ]
