# Generated by Django 2.1.8 on 2019-05-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0011_auto_20190501_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='tags',
        ),
    ]
