# Generated by Django 2.0.8 on 2018-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0012_merge_20180905_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this trigger from firing.'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='pattern',
            field=models.CharField(help_text="The regex pattern to match the full url path with. Groups will be added to the included tag's context.", max_length=255),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='tags',
            field=models.ManyToManyField(help_text='The tags to include when this trigger is fired.', to='wagtail_tag_manager.Tag'),
        ),
    ]
