# Generated by Django 2.2.5 on 2019-09-11 11:16

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0013_auto_20190506_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiedeclaration',
            name='cookie_type',
            field=models.CharField(blank=True, choices=[('necessary', 'Necessary'), ('preferences', 'Preferences'), ('statistics', 'Statistics'), ('marketing', 'Marketing')], help_text='The type of functionality this cookie supports.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('necessary', 'Necessary'), ('preferences', 'Preferences'), ('statistics', 'Statistics'), ('marketing', 'Marketing')], default='necessary', help_text='The purpose of this tag. Will decide if and when this tag is loaded on a per-user basis.', max_length=100),
        ),
    ]
