# Generated by Django 2.0.6 on 2018-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0015_auto_20180913_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_location',
            field=models.CharField(choices=[('0_top_head', 'Top of head tag'), ('1_bottom_head', 'Bottom of head tag'), ('2_top_body', 'Top of body tag'), ('3_bottom_body', 'Bottom of body tag')], default='0_top_head', help_text='Where in the document this tag will be inserted. Only applicable for tags that load instantly.', max_length=14),
        ),
    ]
