# Generated by Django 3.0.3 on 2020-02-10 11:21

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0015_cookieconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiedeclaration',
            name='cookie_type',
            field=models.CharField(blank=True, choices=[('necessary', 'Necessary'), ('preferences', 'Preferences'), ('statistics', 'Statistics'), ('marketing', 'Marketing')], help_text='The type of functionality this cookie supports.', max_length=100, null=True),
        ),
    ]
