# Generated by Django 3.1.1 on 2020-10-28 09:05

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0016_auto_20200210_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookieconsent',
            name='location',
            field=models.URLField(editable=False, max_length=2048),
        ),
    ]
