# Generated by Django 2.0.8 on 2018-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tag_manager', '0016_auto_20180913_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.TextField(help_text='The tag to be added or script to be executed.Will assume the content is a script if no explicit tag has been added.'),
        ),
    ]
