# Generated by Django 4.0.4 on 2022-05-09 12:26

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtail_tag_manager', '0018_alter_constant_id_alter_cookiebarsettings_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions_page', models.ForeignKey(blank=True, help_text='Set the page describing your privacy policy. Every time it changes, the consent given before will be invalidated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
